name: bike_rental
version: 0.1.0
publish_to: none
description: Safara E-Bike
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  image_picker: ^1.1.1
  get: ^4.6.6
  flutter_paystack_plus: ^2.0.4
  qr_code_dart_scan: ^0.8.0
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  uses-material-design: true
